#ifndef CONSTPARAMS_H
#define CONSTPARAMS_H

enum FIGURE_TYPE{FIGURE,LINE,CYCLE,ELLIPSE};    //绘图模式（图形类别）
enum DRAW_STATE{DRAWING,UNDO};  //绘画状态
enum SETLINE{SETBEGIN, SETEND, SETCENTER, SETHANDLE, SETNULL};  //对直线的操作
enum SETCYCLE{CYCLE_CENTER,CYCLE_OUT,CYCLE_HANDLE,CYCLE_NULL};  //对圆的操作
enum SETELLIPSE{ELLIPSE_CENTER,ELLIPSE_OUT,ELLIPSE_HANDLE,ELLIPSE_NULL};    //对椭圆的操作

#endif // CONSTPARAMS_H
