#ifndef CONSTPARAMS_H
#define CONSTPARAMS_H
//#include <QDebug>
//#include <QString>

enum FIGURE_TYPE{FIGURE,LINE,CYCLE,ELLIPSE,POLYGON,PEN,BRUSH};    //绘图模式（图形类别）
enum DRAW_STATE{DRAWING,UNDO};  //绘画状态
enum SETLINE{SETBEGIN, SETEND, SETCENTER, SETHANDLE, SETNULL};  //对直线的操作
enum SETCYCLE{CYCLE_CENTER,CYCLE_OUT,CYCLE_HANDLE,CYCLE_NULL};  //对圆的操作
enum SETELLIPSE{ELLIPSE_CENTER,ELLIPSE_OUT,ELLIPSE_HANDLE,ELLIPSE_NULL};    //对椭圆的操作
enum SETPOLYGON{POLYGON_START,POLYGON_NEXT,POLYGON_CHANGE,POLYGON_NULL,POLYGON_MOVE,POLYGON_ROTATE};    //对多边形的操作

const int BRUSH_WIDTH = 10;
const int PEN_WIDTH = 1;
const double ZOOM_IN = 1.25;
const double ZOOM_OUT = 1/ZOOM_IN;
const double JUDGE_RIDUS = 5;

#endif // CONSTPARAMS_H
